Plex-Engineer/canto-v3

- components/footer/footer.tsx
- removed buttons for commons, mirror
> feat: remove buttons from footer

- app/lending/page.tsx
> merged tables

- app/lp/page.tsx
- components/table/table.module.scss
- components/table/table.tsx
Added Toggle Group and refactored table to take a secondary component to pass in filter
> Add filter to LP table with options "Stable" & "Volatile"

- app/lp/lp.module.scss
- app/lp/page.tsx
Reduce height of rewards card and overall header area
Rename page from "LP" to "Pools"
Reduce the spacing from between the rewards and the table
> Changes to LP layout

- app/lending/components/modal/modal.tsx
- components/amount/amount.module.scss
- components/amount/amount.tsx
- components/text.tsx
This pull request adds the BorrowLimits component to the LendingModal, allowing users to set borrowing limits based on predefined percentages. The component tracks the active limit and updates the borrowing amount accordingly.
> Add BorrowLimits component to LendingModal

- app/explore/components/link.module.scss
- app/explore/components/link.tsx
- app/explore/page.tsx
This PR adds a new component called ExploreLink that is used to display recommended picks in the OutlinksPage. The component includes an image, title, description, and a link to an external website.
> Add ExploreLink component for displaying recommended picks

- hooks/lending/helpers/cTokenTotals.ts
- update apy calculation
- denominator should be (supplied - borrowed)
> bug: update apy calculation

- app/lending/components/highlightCard.tsx
Set the note supplied value to 0 when a balance is less than 0.0000001
> Update display amount for supplied note

- app/lending/page.tsx
- components/footer/components/footerButton.tsx
- components/footer/footer.tsx
- components/nav_bar/navBar.tsx
- components/transactions/TxFlow.tsx
- components/transactions/TxModal.tsx
- provider/analytics.tsx
- stores/transactionStore.tsx
- utils/analytics/analytics.utils.ts
1) Add lending market data when Supply and Borrow Buttons are clicked
2) Add event when transaction flow is retried
2) Track dark vs light mode switch
3) Fix page name property of page view event for explore page
4) Track users visiting socials like twitter, docs etc
5) Track transaction activity modal clicks
> Analytics updates

- app/lp/components/pairRow.tsx
Add information hover for ambient pool rewards in lp
> ambient rewards timer iteration 1

- app/bridge/bridging.tsx
1) Remove "loading fees….."  on bridge in tab
2) The modal should not shift when changing tabs (all three tabs should be the same height)
> bug : remove fee loading on bridge in

- app/lending/page.tsx
- app/lp/page.tsx
- provider/analytics.tsx
- utils/analytics/analytics.utils.ts
Add utility functions to format analytics data for lending and liquidity pools
> Refactor analytics

- app/bridge/bridge.module.scss
- app/bridge/bridging.tsx
- app/bridge/components/bridgeInProgress.tsx
- components/info_bar/info.module.scss
This pull request adds a blinking animation to the loading text in the FeesSection component and fixes the infobar width in the BridgeInProgress component.
> Add blinking animation to loading text and fix infobar width

- components/selector/selector.tsx
On the bridge out select token modal - add a separator between tokens a user has a balance for and those with zero balance.
> Add a separator in select tokens modal

- app/bridge/bridging.tsx
- app/bridge/page.tsx
- app/explore/components/link.module.scss
- app/explore/components/link.tsx
- app/explore/outlinks.module.scss
- app/explore/page.tsx
- app/home.module.scss
- app/layout.tsx
- app/lending/components/highlightCard.module.scss
- app/lending/lending.module.scss
- app/lending/page.tsx
- app/lp/page.tsx
- app/page.tsx
- components/desktop-only/desktop-only.module.scss
- components/footer/footer.module.scss
- components/footer/footer.tsx
- components/modal/modal.module.scss
- components/nav_bar/navBar.tsx
- components/nav_bar/navbar.module.scss
- components/splash/splash.tsx
- components/table/table.module.scss
- public/menu.svg
This pull request includes refactoring of layout and lending components to improve code organization and maintainability. It also includes updates to table styles and modal module styles for responsiveness.
> Refactor layout and lending components

- hooks/pairs/newAmbient/config/ambientPools.ts
- hooks/pairs/newAmbient/helpers/getAmbientPoolsData.ts
- hooks/pairs/newAmbient/useAmbientPools.ts
- add ambient pool
- update APRs to reflect split rewards
> feat: add NOTE/USDC ambient pool 

- app/layout.tsx
This pull request adds the InfoBar component to the layout, allowing for the display of additional information in the user interface.
> Add InfoBar component to layout

- app/explore/components/link.tsx
- app/explore/page.tsx
Add white  background to blank rasa logo so that it looks good in both light and dark modes.
> Update blank rasa logo

- provider/analytics.tsx
- stores/transactionStore.tsx
Add Hash to Transaction Success/Error events
> add hash to transaction analytics

- components/nav_bar/navBar.tsx
- provider/analytics.tsx
- utils/analytics/analytics.utils.ts
1) Add bridge direction to transaction parameters
3) Add page views for staking and governance 
2) Add page view event when query params change
> add bridge direction param to analytics

- app/staking/components/validatorTableRow.tsx
- app/staking/page.tsx
- provider/analytics.tsx
- utils/analytics/analytics.utils.ts
Add analytics for staking transactions and events
> analytics : add staking txs and event analytics

- app/lending/components/cTokenRow.tsx
- app/lending/components/highlightCard.tsx
- app/lending/components/modal/modal.tsx
- app/lending/page.tsx
- hooks/lending/helpers/cTokenTotals.ts
- hooks/lending/interfaces/tokens.ts
Change all lending interest rates to APR.
> update lending interest rates

- app/staking/page.tsx
- app/staking/staking.module.scss
- components/table/table.module.scss
This pull request includes refactoring of the table and staking layout and styles. It also includes bug fixes, changes in column titles, and other table rendering changes.
> Refactor table and staking layout and styles

- app/staking/page.tsx
Sort user staking positions based on the amount staked
> fix: sort user staking positions
